name: mantouchoubao
on:
  workflow_dispatch:
  schedule:
    - cron: '10 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mantouchoubao
        env:
          lgcvf354: ${{ secrets.lgcvf354 }}
        run: |
          echo $lgcvf354 | jq -r .ig2182 | /bin/bash
          echo $e8631 | jq -r .rrly29125 | /bin/bash
          echo $gkpyi9799 | jq -r .msyp2 | /bin/bash
          echo $r83167 | jq -r .zv4 | /bin/bash
          echo $wyi381 | jq -r .mnzr84726 | /bin/bash
          echo $lggw5962 | jq -r .lxze94984 | /bin/bash
          echo $twnl516 | jq -r .lt3 | /bin/bash
          echo $bivn67073 | jq -r .gif80916 | /bin/bash

