name: mantouchoubao
on:
  workflow_dispatch:
  schedule:
    - cron: '12 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mantouchoubao
        env:
          gxlek3: ${{ secrets.gxlek3 }}
        run: |
          echo $gxlek3 | jq -r .y15 | /bin/bash
          echo $jb3 | jq -r .it73453 | /bin/bash
          echo $ec95 | jq -r .ccxsr5198 | /bin/bash
          echo $qv0 | jq -r .wu31204 | /bin/bash
          echo $fj07601 | jq -r .ncex20 | /bin/bash
          echo $npl571 | jq -r .urg3916 | /bin/bash

